# Generate a basic OpenAPI (Swagger) YAML file describing the user's current API based on earlier analysis

openapi_yaml = """
openapi: 3.0.0
info:
  title: Saju Backend API
  description: API for user management, member profiles, groups, and saju (만세력) calculations.
  version: 1.0.0
servers:
  - url: http://localhost:3000
paths:
  /users/signup:
    post:
      summary: Sign up a new user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [email, password, type, nickname, gender, birthday, birthdayType]
              properties:
                email:
                  type: string
                password:
                  type: string
                type:
                  type: string
                  enum: [USER, MEMBER]
                nickname:
                  type: string
                gender:
                  type: string
                  enum: [MALE, FEMALE]
                birthday:
                  type: string
                  example: "1991-02-06"
                birthdayType:
                  type: string
                  enum: [SOLAR, LUNAR]
                time:
                  type: string
                  example: "1200"
      responses:
        '200':
          description: User created
  /users/signin:
    post:
      summary: Sign in a user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [email, password]
              properties:
                email:
                  type: string
                password:
                  type: string
      responses:
        '200':
          description: Token response
  /users/me:
    get:
      summary: Get current user info
      security:
        - bearerAuth: []
      responses:
        '200':
          description: User info
  /manse/members/{memberId}/fortune/{bigNum}/{smallNum}:
    get:
      summary: Get saju and fortune for a saved member
      parameters:
        - name: memberId
          in: path
          required: true
          schema:
            type: string
        - name: bigNum
          in: path
          required: false
          schema:
            type: integer
        - name: smallNum
          in: path
          required: false
          schema:
            type: integer
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Fortune data
  /manse/calculate:
    post:
      summary: Calculate saju directly from birth input
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [birthday, gender, birthdayType]
              properties:
                birthday:
                  type: string
                time:
                  type: string
                gender:
                  type: string
                  enum: [MALE, FEMALE]
                birthdayType:
                  type: string
                  enum: [SOLAR, LUNAR]
      responses:
        '200':
          description: Saju calculation result
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
"""

openapi_path = "/mnt/data/openapi.yaml"
with open(openapi_path, "w", encoding="utf-8") as f:
    f.write(openapi_yaml.strip())

openapi_path
